config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', invitations: 'invitations' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Webhook Routes
  namespace :webhook do
    post 'form/:token' => 'inbound#form', as: :form
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    post 'topics/merge_tickets' => 'topics#merge_tickets', as: :merge_tickets
    patch 'topics/update_tags' => 'topics#update_tags', as: :update_topic_tags
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/unassign_agent' => 'topics#unassign_agent', as: :unassign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    get 'topics/unassign_team' => 'topics#unassign_team', as: :unassign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts
    get 'empty_trash' => 'topics#empty_trash', as: :empty_trash

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'settings/general' => 'settings#general', as: :general_settings
    get 'settings/design' => 'settings#design', as: :design_settings
    get 'settings/theme' => 'settings#theme', as: :theme_settings
    get 'settings/widget' => 'settings#widget', as: :widget_settings
    get 'settings/i18n' => 'settings#i18n', as: :i18n_settings
    get 'settings/email' => 'settings#email', as: :email_settings
    get 'settings/integration' => 'settings#integration', as: :integration_settings
    put 'settings/general' => 'settings#update_general', as: :update_general_settings
    put 'settings/design' => 'settings#update_design', as: :update_design_settings
    put 'settings/theme' => 'settings#update_theme', as: :update_theme_settings
    put 'settings/widget' => 'settings#update_widget', as: :update_widget_settings
    put 'settings/i18n' => 'settings#update_i18n', as: :update_i18n_settings
    put 'settings/email' => 'settings#update_email', as: :update_email_settings
    put 'settings/integration' => 'settings#update_integration', as: :update_integration_settings
    get 'settings/profile' => 'settings#profile', as: :profile_settings
    get 'settings/trash' => 'settings#trash', as: :trash_settings

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    # Export Routes
    get 'backups' => 'backups#index', as: :backups
    get 'backups/export' => "backups/export", as: :export_backup
    get  'backups/download' => "backups/download", as: :download
    delete 'backups/:id(.:format)', :to => 'backups#destroy', as: :delete_backup

    # Import Routes
    resources :imports, only: [:index, :show]
    post 'imports/restore' => "importz/restore", as: :import_restore

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    get 'internal_docs/search' => 'internal_categories#search', as: :internal_docs_search

    patch 'categories/reorganize' => 'categories#reorganize', as: :reorganize
    resources :categories do
      resources :docs, except: [:index, :show]
    end


    resources :internal_categories, only: [:index, :show] do
      resources :internal_docs, only: :show
    end

    resources :docs, except: [:index, :show]
    get 'agent_assistant' => 'agent_assistant#index', as: :agent_assist

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    post 'users/:id/scrub' => 'users#scrub', as: :scrub_user
    scope 'settings' do
      resources :api_keys, except: [:show, :edit, :update]
      resources :groups
      resources :tags
    end
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/reports/team' => 'reports#team', as: :team_reports
    get '/reports/groups' => 'reports#groups', as: :group_reports
    get '/reports' => 'reports#index', as: :reports

    get '/dashboard/blank' => 'dashboard#blank', as: :blank_dashboard

    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/controllers/widget/topics_controller.rb
class Widget::TopicsController < Widget::BaseController

  layout 'widget'
  before_action :allow_iframe_requests

  def new
    @page_title = t(:start_discussion, default: "Start a New Discussion")
    @locale = http_accept_language.compatible_language_from(I18n.available_locales)
    @forums = Forum.ispublic.all
    @topic = Topic.new
    @user = @topic.build_user unless user_signed_in?
    @topic.posts.build
    add_breadcrumb @page_title
  end


  def create

    @forum = Forum.find(1)
    @topic = @forum.topics.new(
      name: params[:topic][:name],
      private: params[:topic][:private],
      doc_id: params[:topic][:doc_id],
      team_list: params[:topic][:team_list],
      channel: 'widget'
    )

    @post = @topic.posts.new(
      body: params[:topic][:posts_attributes]['0'][:body],
      kind: 'first'
    )

    @topic.private = true

    if @topic.create_topic_with_user(params, current_user, @post)
      @user = @topic.user
      @post.update_attribute(:user_id, @user.id)

      # track event in GA
      tracker('Request', 'Post', 'New Topic')
      tracker('Agent: Unassigned', 'New', @topic.to_param)

      UserMailer.new_user(@user.id, @user.reset_password_token).deliver_later if !user_signed_in?
      redirect_to widget_thanks_path
    else
      render 'new'
    end

  end

  def thanks
     @page_title = t(:thank_you, default: 'Thank You!')
  end


end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper

  def ticket_page_title
    concat j ticket_status_label
    concat j new_ticket_button
    concat j ticket_nav_dropdown
  end

  def user_page_title

  end

  def started_by(topic)
    return "Missing User" if topic.user.nil?
    user_name = topic.user.name
    link_to t(:started_by, username: user_name.titleize, default: "Started by #{user_name}"), admin_user_path(topic.user.id), remote: true
  end

  def topic_added_from
    content_tag :small, class: 'less-important hidden-xs' do
      concat t(:topic_added_from, kind: @topic.kind, channel: @topic.channel)
      concat ": #{link_to(@doc.title, edit_admin_category_doc_path(@doc.category_id, @doc.id, lang: I18n.locale))}".html_safe if @doc.present?
    end
  end

  def topic_anonymous_link
    content_tag :div, class: 'pull-right' do
      content_tag :small, class: 'less-important anonymous-link' do
        link_to topic_path(id: @topic.hashid), target: 'blank' do
          content_tag :i, nil, class: 'fas fa-link' 
        end
      end 
    end if AppSettings['settings.anonymous_access'] == "1"
  end

  def ticket_status_label
    content_tag :span, class: "label #{status_class(@status)}", style: 'text-transform: uppercase' do
      status_label(@status)
    end
  end

  def new_ticket_button
    content_tag :span, class: 'hidden-xs pull-right' do
      link_to t(:open_new_discussion, default: 'Open Discussion'), new_admin_topic_path, remote: true, class: 'btn btn-primary' if tickets?
    end
  end

  def ticket_nav_dropdown
    render partial: 'admin/topics/ticket_nav_dropdown'
  end

  def user_priority(user)
    return unless user.priority?
    content_tag :span, class: 'label label-tag', style: 'text-transform: uppercase' do
      user.priority
    end
  end

  def agents_for_select
    User.agents.all.map { |user| [user.name, user.id] }
  end

  def channels_collection
    [
      [t('activerecord.attributes.user.email'), 'email'],
      [t('activerecord.attributes.user.home_phone'), 'phone'],
      [t(:channel_in_person, default: 'In Person'), 'person']
    ]
  end

  def statuses_collection
    statuses = []
    ['new','open','pending','closed'].each do |s|
      statuses << [t(s.to_sym), s]
    end
    statuses
  end

  def ticket_types_collection
    [
      [t('customer_conversation', default: "Customer Conversation"), 'ticket'],
      [t('internal_ticket', default: "Internal Ticket"), 'internal']
    ]
  end

  def ticket_priority_collection
    Topic.priorities.keys.map { |priority| [t("#{priority}_priority"), priority] }
  end

  def ticket_tag_collection
    ActsAsTaggableOn::Tagging.all.where(context: "tags", taggable_type: 'Topic').includes(:tag).map{|tagging| tagging.tag.name }.uniq.sort
  end

  # id of opening or first post in the topic
  def first_post_id(topic)
    first_post = topic.posts.order(created_at: :asc).first
    first_post.present? ? first_post.id : nil
  end

  # show topic tag form
  def topic_tag_form
    return nil if ticket_tag_collection.blank?
    simple_form_for @topic, url: admin_update_topic_tags_path(id: @topic.id, status: params[:status]), remote: true, html: { class: 'form-inline tag-form' } do |f|
      content_tag :div, class: 'row' do
        content_tag :div, class: 'col-md-8' do
          f.input :tag_list, collection: ticket_tag_collection, 
            as: :select, include_blank: false, label: false,
            input_html: { multiple: true, class: '', placeholder: 'click to add tags...' },
            # wrapper_html: { style: 'width: 0' }, 
            data: { 'none-selected-text': t('tag_with', default: 'Tag Ticket'), 'live-search': false, 'width': '150px', dropdownAlignRight: false },
            style: 'width: 280px;'
            
        end
      end
    end
  end

  # tag button label
  def tags_button_label
    if @topic.tag_list.count > 0
      pluralize @topic.tag_list.count, "Tag"
    else
      t(:tag_with, default: "Tag Ticket")
    end
  end

end

app/helpers/topics_helper.rb
# == Schema Information
#
# Table name: topics
#
#  id               :integer          not null, primary key
#  forum_id         :integer
#  user_id          :integer
#  user_name        :string
#  name             :string
#  posts_count      :integer          default(0), not null
#  waiting_on       :string           default("admin"), not null
#  last_post_date   :datetime
#  closed_date      :datetime
#  last_post_id     :integer
#  current_status   :string           default("new"), not null
#  private          :boolean          default(FALSE)
#  assigned_user_id :integer
#  cheatsheet       :boolean          default(FALSE)
#  points           :integer          default(0)
#  post_cache       :text
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  locale           :string
#  doc_id           :integer          default(0)
#  channel          :string           default("email")
#  kind             :string           default("ticket")
#  priority         :integer          default(1)
#

module TopicsHelper

  def badge_for_status(status)
    content_tag(:span, status_label(status), class: "hidden-xs pull-right status-label label #{status_class(status)}")
  end

  def badge_for_private
    content_tag(:span, t(:private, default: 'PRIVATE'), class: 'hidden-xs pull-right status-label label label-private')
  end

  def badge_for_public
    content_tag(:span, t(:public, default: 'PUBLIC'), class: 'hidden-xs pull-right status-label label label-public')
  end

  def control_for_status(status)
    content_tag(:span, "#{status_label(status)} <span class='caret'></span> ".html_safe, class: "change-status btn status-label-button label #{status_class(status)}")
  end

  def control_for_privacy(private_flag)
    str = private_flag ? t(:private, default: 'PRIVATE') : t(:public, default: 'PUBLIC')
    content_tag(:span, "#{str} <span class='caret'></span> ".html_safe, class: 'btn status-label-button change-privacy privacy-label label label-info')
  end

  def status_label(status)
    case status
      when 'new'
        t(:new, default: 'new')
      when 'open'
        t(:open, default: 'open')
      when 'active'
        t(:active, default: 'active')
      when 'assigned'
        t(:mine, default: 'mine')
      when 'closed'
        t(:closed, default: 'resolved')
      when 'pending'
        t(:pending, default: 'pending')
      when 'spam'
        t(:spam, default: 'spam')
      when 'trash'
        t(:trash, default: 'trash')
    end
  end

  def status_class(status)
    case status
      when 'new'
        'label-info'
      when 'open'
        'label-success'
      when 'closed'
        'label-default'
      when 'pending'
        'label-warning'
      when 'spam'
        'label-danger'
      when 'trash'
        'label-danger'
    end
  end

  # Lookup the user set color, if it exists
  def badge_color_from_tag(tag_name)
    tagging = ActsAsTaggableOn::Tag.where('lower(name) = ?', tag_name.downcase).first
    tagging.present? && tagging.color.present? ? 'background-color: ' + tagging.color : ''
  end

  def badge_color_from_topic(topic)
    return '' if topic.team_list.blank?

    tagging = ActsAsTaggableOn::Tag.where('lower(name) = ?', topic.team_list.first.downcase)
    return badge_color_from_tag(tagging.first.name) unless tagging.nil?
  end

  def all_teams
    ActsAsTaggableOn::Tagging.all.where(context: "teams").includes(:tag).where("context = 'teams' and tags.show_on_helpcenter = ?", 'true').references(:tags).map{|tagging| tagging.tag.name.capitalize }.uniq
  end

  def color_sample(tag_name)
    content_tag(:div, '', style: badge_color_from_tag(tag_name), class: 'color-sample label-' + tag_name.first.downcase) + content_tag(:div, tag_name.try(:titleize))
  end

  def extension_whitelist
    return "" unless AppSettings['settings.extension_whitelist'].present?
    
    "'#{[AppSettings['settings.extension_whitelist'].split(',').map(&:strip)].join("', '")}'"
  end

  def extension_blacklist
    return "" unless AppSettings['settings.extension_blacklist'].present?

    "'#{[AppSettings['settings.extension_blacklist'].split(',').map(&:strip)].join("', '")}'".html_safe
  end

end

app/views/topics/_grid.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

  <div class="idea-box col-lg-3 col-md-3 col-sm-4 col-xs-12" data-link="<%= topic_posts_path(grid) %>" id="topic_<%= grid.id %>" >
    <div class="dummy"></div>
    <div class="thumbnail">
      <span class="more-important truncate-ellipsis text-left">
        <%= link_to h(grid.name), topic_posts_path(grid) %>
      </span>
      <div class="text-left">
         <%= grid.posts_count %> comments
      </div>
      <% if grid.forum.allow_post_voting == true %>
      <div id="post-vote-<%= grid.posts.first.id %>" class="grid-vote text-right">
        <%= link_to t(:upvote, count: grid.points), up_vote_path(grid.id), method: :post, remote: true, class: 'topic-vote', data: {voted: grid.to_param}, id: "upvote_#{grid.id}" %>
      </div>
      <% end %>
    </div>

  </div>

app/views/topics/_qna.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<% post = qna.posts.by_votes.first %>

  <div id="post-<%= post.id %>" class="media post-container kind-first<%= " inactive" unless post.active? %>">
    <div class="asked-question">
      <%= distance_of_time_in_words(Time.now,qna.created_at) %> ago <%= post_message(qna.posts.first) %>
    </div>
    <h4 class="qna"><%= link_to h(qna.name), topic_posts_path(qna) -%></h4>
    <div class="pull-left">
      <%= avatar_image(post.user, size=40) %>
  	</div>
  	<div class="media-body media-right">
  		<span class="hidden-sm hidden-md hidden-lg"><%= last_active_time(post.created_at) %><br/></span>
  		<span id="row-<%= post.id %>"  class="post-menu post-menu-<%= post.id %> btn-group">
        <%= post_message(post) %>
  		</span>

  		<div id="post-body-<%= post.id %>" class="post-body less-important text-left">
  			<span class="shorten"><%= simple_format(post.body) -%></span>
        <% if post.topic.forum.allow_post_voting == true %>
  			<div id="post-vote-<%= post.id %>" class="btn btn-default">
  				<% if post.kind == 'first' %>
  				<%= link_to t(:upvote, count: post.topic.points), up_vote_path(post.topic.id), method: :post, remote: true, class: 'topic-vote', data: {voted: post.topic.to_param}, id: "upvote_#{post.topic.id}" %>
  				<% else %>
  				<%= link_to t(:upvote, count: post.points), post_vote_path(post.id), method: :post, remote: true, class: 'post-vote', data: {voted: post.topic.to_param}, id: "upvote_#{post.topic.id}" %>
  				<% end %>
  			</div>
  			<% end %>

  		</div>



  	</div>
  </div>

<hr/>

app/views/topics/_ticket.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<div class="ticket border-bottom row vcenter">
  <div class="col-md-8 text-left">
    <span class="truncate-ellipsis">
      <%= link_to "##{ticket.id}- #{ticket.name.capitalize}", ticket_path(ticket) -%>
    </span>
  </div>
  <div class="col-md-1">
    <%= badge_for_status(ticket.current_status) %>
  </div>
  <div class="col-md-1">
    <div class="label label-count hidden-xs pull-left"><%= ticket.posts_count %></div>
  </div>
  <div class="last-active less-important col-md-2 text-right">

    <%= last_active_time(ticket.updated_at) %>
  </div>
</div>

app/views/topics/_topic.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<tr id="topic_<%= topic.id %>" class="topic link-row">
  <% if topic.forum.allow_topic_voting == true %>
    <td>

      <div class="voting-widget">
        <!--<span class="glyphicon glyphicon-plus-sign"></span>-->
        <div class="vote-icon glyphicon glyphicon-chevron-up"></div>
        <div class="topic-points"><%= link_to topic.points, up_vote_path(topic.id), method: :post, remote: true, class: 'topic-vote', data: {voted: topic.to_param}, id: "upvote_#{topic.id}" %></div>
      </div>
    </td>
  <% end %>
  <td>
    <span class="more-important truncate-ellipsis"><%= link_to h(topic.name), topic_posts_path(topic) -%></span>
    <span class="less-important"><%= t(:started_by, :username => topic.user.name.titleize) %></span>
  </td>
  <td>
    <span class="label label-count hidden-xs"><%= topic.posts_count %></span>
  </td>
  <td class="last-active less-important text-right">
    <%= last_active_time(topic.last_post_date) %>
  </td>
</tr>

app/views/topics/index.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<%- title "#{AppSettings['settings.site_name']}: #{@page_title}" %>

<% if @forum.layout == "table" %>

<table id="forums" class="table-hover">

  <% if @forum.allow_topic_voting == true %>
  <col width="5%">
  <% end %>
  <col>
  <col width="5%">
  <col width="10%">

  <tbody>
    <tr>
      <% if @forum.allow_topic_voting == true %>
      <th colspan="3">
      <% else %>

      <th colspan="2">
      <% end %>
        <%= t(:topic) %></th>
  	  <th class="text-right"><%= t(:last_activity) %></th>
    </tr>
    <%= render :partial => 'topic', :collection => @topics %>
  </tbody>
</table>

<% elsif @forum.layout == "grid" %>
<div id="featured-categories" class="row">
  <%= render :partial => 'grid', :collection => @topics %>
</div>

<% elsif @forum.layout == "qna" %>
<div class="row">
	<div class="col-md-12">
    <div id="qnas">
      <%= render :partial => 'qna', :collection => @topics %>
    </div>
  </div>
</div>
<% end %>



<div class="text-right">
	<%= paginate @topics %>
</div>

<div>
  <% if user_signed_in? %>
    <span class="hidden-xs pull-right"><%= link_to t(:start_discussion, default: "Start Discussion"), new_topic_path, class: 'btn btn-primary' %></span>
  <% else %>
    <span class="hidden-xs pull-right"><%= link_to t(:start_discussion, default: "Start Discussion"), '#', data: {toggle: "modal", target: "#login-modal"}, class: 'btn btn-primary' %></span>
  <% end %>
</div>

app/views/topics/show.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<%- title "#{AppSettings['settings.site_name']}: #{@page_title}" %>

<div id="ticket-info" class="row">
  <div class="col-md-3 col-sm-3 hidden-xs" id="left-col-user-info">
    <div class="doc-meta">
      <div class="more-important meta-header">Ticket Number:</div>
      <div class="less-important"><%= @topic.id %></div>
    </div>
    <div class="doc-meta">
      <div class="more-important meta-header"><%= I18n.t('assigned_to_label', default: "Assigned To") %>:</div>
      <div class="less-important">
        <% unless @topic.assigned_user.nil? %>
          <%= avatar_image(@topic.assigned_user, size=40) %>
          <%= @topic.assigned_user.name.titleize %>
        <% else %>
          Unassigned
        <% end %>
      </div>
    </div>
    <div class="doc-meta">
      <div class="more-important meta-header">Opened On:</div>
      <div class="less-important"><%= @topic.created_at %></div>
    </div>
  </div>
  <div id="ticket-controls" class="col-xs-12 col-sm-9 col-md-9 col-lg-9">
    <script>
      Helpy.messages = '<%= j t(:collapsed_messages, count: @posts.count-2) %>';
    </script>
    <div id="posts">
      <%= render :partial => 'posts/post', :collection => @posts %>
    </div>
    <% if user_signed_in? %>
      <div class="add-form">
      <h4><%= I18n.t("reply", default: "Reply to this Topic") %></h4>
      <%#= error_messages_for :post -%>
      <%= bootstrap_form_for @topic.posts.new, :url => topic_posts_path(@topic), :remote => true do |f| -%>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token -%>
        <%= f.hidden_field 'kind', value: 'reply' %>
        <%= hidden_field_tag :client_id %>
        <%= f.text_area :body, :rows => 8, :cols => 160, skip_label: true, class: 'disable-empty' -%></p>
        <%= f.attachinary_file_field :screenshots if cloudinary_enabled? %>
        <%= f.file_field :attachments, multiple: true unless cloudinary_enabled? %>				
        <%= f.submit I18n.t('submit_reply', default: 'Post Reply'), class: 'btn btn-warning' -%>
      <% end -%>
      </div>
    <% end -%>
  </div>
</div>

app/views/topics/tag.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<div id="breadcrumbs">
  <%= link_to 'Forums', forums_path -%> > <strong>Tagged with <%= h params[:id] -%></strong>
</div>

<div class="Paginator" align="right">
	<%#= will_paginate @topics %>
</div>

<table id="topics">

  <col width="55%">
  <col width="5%">
  <col width="10%">
  <col width="5%">
  <col width="20%">

  <tr>
    <th colspan="2">Topic</th>
    <th>Status</th>
    <th>Replies</th>
	<th>Last Post</th>
  </tr>
  <%= render :partial => 'topic', :collection => @topics %>
</table>

<div class="Paginator" align="right">
	<%#= will_paginate @topics %>
</div>