config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', invitations: 'invitations' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Webhook Routes
  namespace :webhook do
    post 'form/:token' => 'inbound#form', as: :form
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    post 'topics/merge_tickets' => 'topics#merge_tickets', as: :merge_tickets
    patch 'topics/update_tags' => 'topics#update_tags', as: :update_topic_tags
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/unassign_agent' => 'topics#unassign_agent', as: :unassign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    get 'topics/unassign_team' => 'topics#unassign_team', as: :unassign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts
    get 'empty_trash' => 'topics#empty_trash', as: :empty_trash

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'settings/general' => 'settings#general', as: :general_settings
    get 'settings/design' => 'settings#design', as: :design_settings
    get 'settings/theme' => 'settings#theme', as: :theme_settings
    get 'settings/widget' => 'settings#widget', as: :widget_settings
    get 'settings/i18n' => 'settings#i18n', as: :i18n_settings
    get 'settings/email' => 'settings#email', as: :email_settings
    get 'settings/integration' => 'settings#integration', as: :integration_settings
    put 'settings/general' => 'settings#update_general', as: :update_general_settings
    put 'settings/design' => 'settings#update_design', as: :update_design_settings
    put 'settings/theme' => 'settings#update_theme', as: :update_theme_settings
    put 'settings/widget' => 'settings#update_widget', as: :update_widget_settings
    put 'settings/i18n' => 'settings#update_i18n', as: :update_i18n_settings
    put 'settings/email' => 'settings#update_email', as: :update_email_settings
    put 'settings/integration' => 'settings#update_integration', as: :update_integration_settings
    get 'settings/profile' => 'settings#profile', as: :profile_settings
    get 'settings/trash' => 'settings#trash', as: :trash_settings

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    # Export Routes
    get 'backups' => 'backups#index', as: :backups
    get 'backups/export' => "backups/export", as: :export_backup
    get  'backups/download' => "backups/download", as: :download
    delete 'backups/:id(.:format)', :to => 'backups#destroy', as: :delete_backup

    # Import Routes
    resources :imports, only: [:index, :show]
    post 'imports/restore' => "importz/restore", as: :import_restore

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    get 'internal_docs/search' => 'internal_categories#search', as: :internal_docs_search

    patch 'categories/reorganize' => 'categories#reorganize', as: :reorganize
    resources :categories do
      resources :docs, except: [:index, :show]
    end


    resources :internal_categories, only: [:index, :show] do
      resources :internal_docs, only: :show
    end

    resources :docs, except: [:index, :show]
    get 'agent_assistant' => 'agent_assistant#index', as: :agent_assist

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    post 'users/:id/scrub' => 'users#scrub', as: :scrub_user
    scope 'settings' do
      resources :api_keys, except: [:show, :edit, :update]
      resources :groups
      resources :tags
    end
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/reports/team' => 'reports#team', as: :team_reports
    get '/reports/groups' => 'reports#groups', as: :group_reports
    get '/reports' => 'reports#index', as: :reports

    get '/dashboard/blank' => 'dashboard#blank', as: :blank_dashboard

    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < Admin::BaseController

  include StatsHelper
  before_action :verify_admin
  before_action :get_all_teams

  before_action :date_from_params
  before_action :scope_data
  before_action :set_interval
  before_action :set_timezone

  def index
    @number_of_days = (@end_date.to_date - @start_date.to_date).round
    if @number_of_days == 1
      get_hourly_stats
    else
      get_daily_stats
    end
  end

  def team
    @topics = Topic.undeleted.where('topics.created_at >= ? AND topics.created_at <= ?', @start_date, @end_date)
    @topic_count = @topics.count

    # Note: Cannot use 'posts_count' counter cache; we only count posts with kind='reply' (not 'first' or 'note').
    responded_topic_ids = @topics
      .joins(:posts)
      .where(posts: { kind: 'reply' })
      .group('topics.id')
      .having('COUNT(posts.id) > 0')
      .ids
    @responded_topics = Topic.where(id: responded_topic_ids)
    @closed_topic_count = @topics.closed.count

    @posts = Post.where('created_at >= ? AND created_at <= ?', @start_date, @end_date)

    delays = @responded_topics.map { |t| t.posts.second.created_at - t.created_at }

    @median_first_response_time = median(delays) unless delays.empty?
  end

  def groups
  end

  private

  def set_interval
    @interval = case params[:label]
                  when 'today'
                    t('today')
                  when 'yesterday'
                    t('yesterday')
                  when 'this_week'
                    t('this_week')
                  when 'last_week'
                    t('last_week')
                  when 'this_month'
                    t('this_month')
                  when 'last_month'
                    t('last_month')
                  when 'interval'
                    "Between #{@start_date.to_date} and #{@end_date.to_date}"
                  else
                    t('this_week')
                end

  end

  def scope_data
    @scoped_stats = Topic.where('topics.created_at >= ? AND topics.created_at <= ?', @start_date, @end_date)
    @scoped_posts = Post.where('created_at >= ? AND created_at <= ?', @start_date, @end_date)
  end

  def get_daily_stats
    @tickets = Topic.group_by_day(:created_at, range: @start_date..@end_date).count
    @closed = Topic.where(current_status: 'closed').group_by_day(:created_at, range: @start_date..@end_date).count
    @actions = Post.group_by_day(:created_at, range: @start_date..@end_date).count
    get_total_stats
  end

  def get_hourly_stats
    unless @scoped_stats.nil?
      @tickets = @scoped_stats.group_by_hour_of_day(:created_at).count
      @closed = @scoped_stats.where(current_status: 'closed').group_by_hour_of_day(:created_at).count
      @actions = @scoped_posts.group_by_hour_of_day(:created_at).count
    end
    get_total_stats
  end

  def get_total_stats
    @total_tickets = @scoped_stats.count
    @total_replies = @scoped_posts.where(kind: 'reply').count
    @total_closed = @scoped_stats.where(current_status: 'closed').count
    @total_activities = @scoped_posts.count
    filtered_stats = @scoped_stats.where("current_status = ? AND closed_date IS NOT NULL", 'closed')
    arr_time_differences = filtered_stats.map {|t| t.closed_date - t.created_at} unless filtered_stats.nil?
    @median_close_time = median(arr_time_differences).round unless arr_time_differences.size == 0
  end

  def set_timezone
    Groupdate.time_zone = current_user.time_zone
  end

end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper

  def assigned_agent_stats(scoped_stats)
    User.agents.map { |a| [ a.name, scoped_stats.where(assigned_user_id: a.id).count] }
  end

  def tickets_by_status(scoped_stats)
    scoped_stats.group(:current_status).count
  end

  def tickets_by_group(scoped_stats)
    @teams = @all_teams.sort_by!{ |e| ActiveSupport::Inflector.transliterate(e.downcase) }.map { |name| [name, scoped_stats.tagged_with(name).count] }
  end

  def percent_resolved(fraction, total, default=0)
    total > 0 ? number_to_percentage((fraction.to_f/total.to_f)*100, precision: 0) : number_to_percentage(default, precision: 0)
  end

  def per_day(number, days, default=0)
    if days == 0
      "-"
    else
      (number.to_f/days.to_f).round(1)
    end
  end

  # NOTE Does not appear to be used currently.  Needs work to return the color.
  def group_colors(scoped_stats)
    # team_tag_ids = ActsAsTaggableOn::Tagging.all.where(context: "teams").includes(:tag).map{|tagging| tagging.tag.id }.uniq
    # @teams = ActsAsTaggableOn::Tag.where("id IN (?)", team_tag_ids)
    @all_teams.map { |g| g.color }
  end

end

app/views/admin/reports/_agent_stats.html.erb
<div class="col-md-<%= @cols %> col-sm-<%= @cols %> text-center agent">

  <div class="agent-id">
    <div class="agent-image">
      <%= link_to avatar_image(agent_stats.assigned_user, size=80), admin_user_path(id: agent_stats.assigned_user_id) if agent_stats.assigned_user.present? %>
    </div>
    <div class="agent-name">
      <% topic_count = @topics.where(assigned_user: agent_stats.assigned_user).count %>
      <h4>
        <%= agent_stats.assigned_user.try(:name).split(' ')[0].titleize || t('no_agent', default: 'No Agent').html_safe %><br/>
        <small><%= t("#{agent_stats.assigned_user.try(:role)}_role") %></small>
      </h4>
    </div>
    <div class="tag-list">
      <% tag_listing(agent_stats.assigned_user.team_list, "user") %>
    </div>
  </div>

  <div class="agent-assigned-count agent-stat">
    <h4><%= topic_count.zero? ? '-' : topic_count %><br/>
    <small><%= t('assigned_topics', default: "Assigned Topics") %></small>
  </div>

  <div class="agent-responded agent-stat">
    <% responded_topic_count = @responded_topics.where(assigned_user: agent_stats.assigned_user).length %>
    <h4 title="Responded to <%= responded_topic_count %> / <%= topic_count %>">
      <% if topic_count.zero? %>
        -
      <% else %>
        <%= number_to_percentage(responded_topic_count.to_f / topic_count.to_f * 100.00, precision: 1)  %>
      <% end %>
      <br/>
      <small><%= t('responded', default: "Responded") %></small>
    </h4>
  </div>

  <div class="agent-closed agent-stat">
    <% closed_topic_count = Topic.undeleted.where(assigned_user: agent_stats.assigned_user).closed.count %>
    <h4 title="<%= closed_topic_count %> / <%= topic_count %> Closed">
      <% if topic_count.zero? %>
        -
      <% else %>
        <%= number_to_percentage(closed_topic_count.to_f / topic_count.to_f * 100.00, precision: 1)  %>
      <% end %>
      <br/>
      <small><%= t('closed', default: "Closed") %></small>
    </h4>
  </div>

  <div class="agent-replies agent-stat">
    <% posts_count = @posts.where(user: agent_stats.assigned_user, kind: 'reply').count %>
    <h4><%= posts_count.zero? ? '-' : posts_count %>
    <br/><small><%= t('replies', default: "Replies") %></small></h4>
  </div>

  <div class="agent-response-time agent-stat">
    <% delays = @responded_topics.where(assigned_user: agent_stats.assigned_user).map { |t| t.posts.second.created_at - t.created_at } %>
    <h4>
      <% if delays.empty? %>
        -
      <% else %>
        <%= distance_of_time_in_words median(delays) %>
      <% end %>
      <br/>
      <small><%= t('median_time', default: "Median Time to first response") %></small>
    </h4>
  </div>

  <div class="agent-stat" data-hook="agent-stat">
  </div>

</div>

app/views/admin/reports/_date_selector.html.erb
<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
  <li><%= link_to t("today", default: "Today"), send(path, start_date: Time.zone.today.at_beginning_of_day, end_date: Time.zone.tomorrow.at_beginning_of_day, label: 'today') %></li>
  <li><%= link_to t("yesterday", default: "Yesterday"), send(path, start_date: Time.zone.yesterday.at_beginning_of_day, end_date: Time.zone.today.at_beginning_of_day, label: 'yesterday') %></li>
  <li><%= link_to t("this_week", default: "This Week"), send(path, start_date: Time.zone.today.midnight.at_beginning_of_week, end_date: Time.zone.today.midnight.at_end_of_week, label: 'this_week') %></li>
  <li><%= link_to t("last_week", default: "Last Week"), send(path, start_date: Time.zone.today.last_week.midnight.at_beginning_of_week, end_date: Time.zone.today.last_week.midnight.at_end_of_week, label: 'last_week') %></li>
  <li><%= link_to t("this_month", default: "This Month"), send(path, start_date: Time.zone.today.midnight.at_beginning_of_month, end_date: Time.zone.today.midnight.at_end_of_month, label: 'this_month') %></li>
  <li><%= link_to t("last_month", default: "Last Month"), send(path, start_date: Time.zone.today.last_month.midnight.at_beginning_of_month, end_date: Time.zone.today.last_month.midnight.at_end_of_month, label: 'last_month') %></li>
  <hr>
  <li>
    <%= form_tag send(path), class: 'form-horizontal dropdown-form', method: :get do %>
      <%= hidden_field_tag :label, 'interval' %>
      <div class="form-group">
        <%= label_tag t(:insight_start_range, default: 'Start:'), nil, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="input-group date">
            <%= text_field_tag :start_date, nil, class: 'form-control' %>
            <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag t(:insight_end_range, default: 'End:'), nil, class: 'col-sm-2 control-label' %>
        <div class="col-sm-10">
          <div class="input-group date">
            <%= text_field_tag :end_date, nil, class: 'form-control' %>
            <span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= submit_tag t(:insight_filter, default: 'Filter'), class: 'btn btn-default' %>
        </div>
      </div>
    <% end %>
  </li>
</ul>

app/views/admin/reports/_report_header.html.erb
<div class="report-header row">
  <div class="col-md-12 clearfix">
    <h3>
      <%= show_responsive_nav %>
      <%= report_name %>:
      <%= content_tag :span, class: "dropdown pull-right" do %>
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
          <%= @interval.sentence_case %>
          <span class="caret"></span>
        </button>
        <%= render partial: 'admin/reports/date_selector', locals: { path: report_path } %>
      <% end %>
    </h3>
  </div>
</div>

app/views/admin/reports/_reports_nav.html.erb
<div class="reports-nav" data-hook="reports-left-nav">
<%= content_tag :div, class: "left-nav-header" do %>
  <%= content_tag :span, t('ticketing_reports'), class: 'tiny-header' %>
  <%= hide_responsive_nav %>
<% end %>
<%= content_tag :ul, class: "list-unstyled nav-items" do %>
  <%= content_tag :li, link_to(t('activity_report'), admin_reports_path(start_date: @start_date, end_date: @end_date, label: params[:label])), class: 'report-link nav-item' %>
  <%= content_tag :li, link_to(t('group_report'), admin_group_reports_path(start_date: @start_date, end_date: @end_date, label: params[:label])), class: 'report-link nav-item' %>
<% end %>
<%= content_tag :div, class: "left-nav-header" do %>
  <%= content_tag :span, t('team_reports'), class: 'tiny-header' %>
<% end %>
<%= content_tag :ul, class: "list-unstyled nav-items" do %>
  <%= content_tag :li, link_to(t('team_insights'), admin_team_reports_path(start_date: @start_date, end_date: @end_date, label: params[:label])), class: 'report-link nav-item' %>
<% end %>
</div>

app/views/admin/reports/groups.html.erb
<% title t('group_report') %>

<div class="row">
  <div id="admin-left-nav" class="col-md-3 hidden-xs hidden-sm">
    <%= render partial: 'admin/reports/reports_nav' %>
  </div>
  <div class="col-md-9 main-panel">
    <%= render partial: 'admin/reports/report_header', locals:
        {
          report_name: t('group_report', site_name: AppSettings['settings.site_name'], default: "Group Report"),
          report_path: "admin_group_reports_path"
        } %>
    <div class="row">
      <div class="col-md-12">
        <%= column_chart tickets_by_group(@scoped_stats) %>
        <table width="100%" id="reports">
          <col width="80%">
          <col width="0%">
          <col width="20%">
          <thead>
            <th><%= t('group') %></th>
            <th>
            <th class="text-right"><%= t('tickets') %></th>
          </thead>
          <%
          @teams.each do |team|
          %>
          <tr>
            <td><span class="more-important"><%= team[0].capitalize %></span><br/><span class="less-important"></span></td>
            <td></td>
            <td><%= content_tag :h3, team[1], class: 'pull-right' %></td>
          </tr>
          <% end %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/admin/reports/index.html.erb
<% title t('activity_report') %>
<div class="row">
  <div id="admin-left-nav" class="col-md-3 hidden-xs hidden-sm">
    <%= render partial: 'admin/reports/reports_nav' %>
  </div>
  <div class="col-md-9 main-panel">
    <%= render partial: 'admin/reports/report_header', locals:
        {
          report_name: t('activity_report', site_name: AppSettings['settings.site_name'], default: "Activity Report"),
          report_path: "admin_reports_path"
        } %>


    <div class="row">
      <div class="big-stats">
        <div class="col-md-6 col-xs-6 text-right">
          <h2><%= percent_resolved(@total_closed, @total_tickets) %></h2>
          <span class="tiny-header"><%= t('percent_resolved', default: "Percent Resolved")%></span>
        </div>
        <div class="col-md-6 col-xs-6 text-left">
          <h2><%= @median_close_time.nil? ? distance_of_time_in_words(0) : distance_of_time_in_words(@median_close_time) %></h2>
            <span class="tiny-header"><%= t('average_resolution_time', default: 'Average Resolution Time') %></span>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= area_chart [
          { name: t('tickets'), data: @tickets },
          { name: t('closed'), data: @closed },
          { name: t('helpers.actions'), data: @actions },
          ],
          legend: "bottom",
          # title: "Tickets Received",
          library: { pointRadius: 0 }
          %>

        <%#= pie_chart [
          # ["Closed", @scoped_stats.sum(:number_closed)],
          ["Unanswered", @scoped_stats.sum(:number_of_tickets)-@scoped_stats.sum(:number_closed)],
          ["Responded", @scoped_stats.sum(:number_of_tickets)-@scoped_stats.sum(:responded)]
          ], library: {cutoutPercentage: 50} %>

        <table width="100%" id="reports">
          <col width="80%">
          <col width="0%">
          <col width="20%">

          <tr>
            <td><span class="more-important"><%= t('new_tickets', default: "New Tickets") %></span><br/>
              <span class="less-important"><%= t('new_tickets_explain', default: 'The number of new tickets your Helpy has received in this period.') %></span></td>
            <td></td>
            <td><%= content_tag :h3, @total_tickets, class: 'pull-right' %></td>
          </tr>
          <tr>
            <td><span class="more-important"><%= t('tickets_per_day', default: "Tickets per Day") %></span><br/>
              <span class="less-important"><%= t('tickets_per_day_explain', default: "The number of tickets your Helpy averages per day.") %></span></td>
            <td></td>
            <td><%= content_tag :h3, per_day(@total_tickets, @number_of_days), class: 'pull-right' %></td>
          </tr>
          <tr>
            <td><span class="more-important"><%= t('replies', default: 'Replies') %></span><br/><span class="less-important"><%= t('replies_explain', default: 'The number of replies your agents have written in this period.') %></span></td>
            <td></td>
            <td><%= content_tag :h3, @total_replies, class: 'pull-right' %></td>
          </tr>
          <tr>
            <td><span class="more-important"><%= t('ticket_actions') %></span><br/><span class="less-important"><%= t('actions_explain', default: 'The total number of actions (replies or internal notes) in this period. A good indication of how busy your Helpy is overall.') %></span></td>
            <td></td>
            <td><%= content_tag :h3, @total_activities, class: 'pull-right' %></td>
          </tr>
          <tr>
            <td><span class="more-important"><%= t('closed') %></span><br/><span class="less-important"><%= t('closed_explain', default: 'The number of tickets closed during this period. Should be close to the number of new tickets for prior periods.') %></span></td>
            <td></td>
            <td><%= content_tag :h3, @total_closed, class: 'pull-right' %></td>
          </tr>
        </table>
      </div>
    </div>
    <!-- <div class="row">
      <div class="col-md-6">
        <%#= pie_chart assigned_agent_stats(@scoped_stats), title: "Assigned Agents" %>
      </div>
      <div class="col-md-6">
        <%#= pie_chart tickets_by_group(@scoped_stats), title: "Groups" %>
      </div>
    </div> -->
  </div>
</div>

app/views/admin/reports/team.html.erb
<% title "#{admin_title} #{t('team_insights', site_name: AppSettings['settings.site_name'])}" %>

<div class="team-members row">
  <div class="col-md-2">
    <%= render partial: 'admin/reports/reports_nav' %>
  </div>
  <div class="col-md-10 main-panel">

    <%= render partial: 'admin/reports/report_header', locals:
        {
          report_name: t('team_insights', site_name: AppSettings['settings.site_name']),
          report_path: "admin_team_reports_path"
        } %>

    <div class="insights-blurb">
      <h2 style="margin-top: 0;">
      <small>
        <% if @topic_count > 0 %>
          <%= t('insights_blurb_one', count: @topic_count, period: h(@interval.sentence_case)).html_safe %>
          <%= t('insights_blurb_two', number_replied: @responded_topics.count, percentage_replied: number_to_percentage(@responded_topics.count.to_f / @topic_count.to_f * 100.00, precision: 1)).html_safe %>
          <%= t('insights_blurb_three_html', response_time: distance_of_time_in_words(@median_first_response_time)) if @responded_topics.count > 0 %>
        <% else %>
          <%= t('no_discussions', period: h(@interval)).html_safe %>
        <% end %>
      </small>
      </h2>
    </div>
    <div class"row">

      <% @agents = Topic.undeleted.select(:assigned_user_id).where('assigned_user_id IS NOT NULL').distinct %>
      <% @agents.each do |t| %>

      <%
        # figure out ideal column width
        # this could (and maybe should) be done with javascript
        @cols = case @agents.count
        when 1
          5
        when 2
          4
        when 3
          3
        when 4
          2
        else
          2
        end
      %>
      <%= render partial: 'agent_stats', object: t %>
      <% end %>
    </div>
  </div>
</div>

</div>