config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords', invitations: 'invitations' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Webhook Routes
  namespace :webhook do
    post 'form/:token' => 'inbound#form', as: :form
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    post 'topics/merge_tickets' => 'topics#merge_tickets', as: :merge_tickets
    patch 'topics/update_tags' => 'topics#update_tags', as: :update_topic_tags
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/unassign_agent' => 'topics#unassign_agent', as: :unassign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    get 'topics/unassign_team' => 'topics#unassign_team', as: :unassign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts
    get 'empty_trash' => 'topics#empty_trash', as: :empty_trash

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'settings/general' => 'settings#general', as: :general_settings
    get 'settings/design' => 'settings#design', as: :design_settings
    get 'settings/theme' => 'settings#theme', as: :theme_settings
    get 'settings/widget' => 'settings#widget', as: :widget_settings
    get 'settings/i18n' => 'settings#i18n', as: :i18n_settings
    get 'settings/email' => 'settings#email', as: :email_settings
    get 'settings/integration' => 'settings#integration', as: :integration_settings
    put 'settings/general' => 'settings#update_general', as: :update_general_settings
    put 'settings/design' => 'settings#update_design', as: :update_design_settings
    put 'settings/theme' => 'settings#update_theme', as: :update_theme_settings
    put 'settings/widget' => 'settings#update_widget', as: :update_widget_settings
    put 'settings/i18n' => 'settings#update_i18n', as: :update_i18n_settings
    put 'settings/email' => 'settings#update_email', as: :update_email_settings
    put 'settings/integration' => 'settings#update_integration', as: :update_integration_settings
    get 'settings/profile' => 'settings#profile', as: :profile_settings
    get 'settings/trash' => 'settings#trash', as: :trash_settings

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    # Export Routes
    get 'backups' => 'backups#index', as: :backups
    get 'backups/export' => "backups/export", as: :export_backup
    get  'backups/download' => "backups/download", as: :download
    delete 'backups/:id(.:format)', :to => 'backups#destroy', as: :delete_backup

    # Import Routes
    resources :imports, only: [:index, :show]
    post 'imports/restore' => "importz/restore", as: :import_restore

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    get 'internal_docs/search' => 'internal_categories#search', as: :internal_docs_search

    patch 'categories/reorganize' => 'categories#reorganize', as: :reorganize
    resources :categories do
      resources :docs, except: [:index, :show]
    end


    resources :internal_categories, only: [:index, :show] do
      resources :internal_docs, only: :show
    end

    resources :docs, except: [:index, :show]
    get 'agent_assistant' => 'agent_assistant#index', as: :agent_assist

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    post 'users/:id/scrub' => 'users#scrub', as: :scrub_user
    scope 'settings' do
      resources :api_keys, except: [:show, :edit, :update]
      resources :groups
      resources :tags
    end
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/reports/team' => 'reports#team', as: :team_reports
    get '/reports/groups' => 'reports#groups', as: :group_reports
    get '/reports' => 'reports#index', as: :reports

    get '/dashboard/blank' => 'dashboard#blank', as: :blank_dashboard

    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

app/controllers/admin/internal_categories_controller.rb
class Admin::InternalCategoriesController < Admin::BaseController

  def index
    @categories = Category.internally.without_system_resource.with_translations(I18n.locale).ordered
  end

  def show
    @category = Category.internally.without_system_resource.active.where(id: params[:id]).first
    if @category
      if I18n.available_locales.count > 1
        @docs = @category.docs.ordered.active.with_translations(I18n.locale).page params[:page]
      else
        @docs = @category.docs.ordered.active.page params[:page]
      end

      @page_title = @category.name

      generate_page_breadcumbs
    else
      redirect_to controller: '/errors', action: 'not_found'
    end
  end

  private

  def generate_page_breadcumbs
    add_breadcrumb t(:internal_content, default: "Internal Content"), admin_internal_categories_path
    add_breadcrumb @docs.category.name, category_path(@docs.first.category) if !@doc.nil? && @doc.first.category.name
  end
end

app/helpers/admin/internal_categories_helper.rb
module Admin::InternalCategoriesHelper
end

app/views/admin/internal_categories/index.html.erb
  <div id="featured-categories" class="row">
    <h2 class="text-center space-h2"><%= t(:internal_content, default: "Internal Content") %></h2>
    <% if @categories.count > 0 && Doc.all.with_translations(I18n.locale).count > 0 && knowledgebase? %>
      <div id="home-topics" class="col-md-12">
      <% @categories.each do |category| %>
        <% if category.docs.with_translations(I18n.locale).count > 0 %>
          <div class="topic-box col-lg-3 col-md-3 col-sm-4 col-xs-12" data-link="<%= admin_internal_category_path(category) %>">
            <div class="dummy"></div>
            <div class="thumbnail">
              <h5 class="category-header text-center"><span class="category-icon glyphicon glyphicon-<%= category.icon %>"></span><br/><%= link_to category.name, admin_internal_category_path(category), id: "category-#{category.id}"  %><br/></h5>
              <p class="text-center less-important hidden-xs"><%= category.meta_description %></p>
            </div>
          </div>
        <% end %>
      <% end %>
      </div>
    <% else %>
      <div class="row">
        <div class="alert alert-info" role="alert">
          <div class="row text-center">
            <i class="fas fa-exclamation-circle fa-3x" aria-hidden="true"></i>

            <h4><%= t(:no_internal_content_title, default: "There's no internal documentation written yet!") %>"</h4>
          </div>
          <div class="row text-center">
            <div class="col-xs-12">
              <p><%= t(:no_internal_content_text,
                        default: "Dont worry ! To contribute with the internal documentation, go to Helpcenter > Content. And add a new Internal type of Category, then share your knowledge with your team writing some Docs!") %> </p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/admin/internal_categories/show.html.erb
<div class="row content-row">
  <%= render 'layouts/internal_knowledgebase_page_title' %>

  <div class="col-md-10 col-md-offset-1">
    <div class="row">
      <table id="forums" class='table-hover'>
        <col>
        <tbody id="categories">
          <% @docs.each do |doc| %>
              <tr class="item main-panel" style="margin-bottom: 5px;">
                <td>
                  <span class="more-important">
                    <%= link_to doc.title, admin_internal_category_internal_doc_path(doc.category, doc) %>
                  </span>
                </td>
              </tr>
          <% end %>
      </tbody>
        <% if @docs.count == 0 %>

          <div class="text-center verticalness">
            <%= t(:nothing_here) %>
          </div>

        <% end %>
      </table>
    </div>

    <div class="row">
      <div class="col-md-9 text-left">
        <%= paginate @docs %>
      </div>
    </div>

  </div>

</div>